"""Generate the portable, static presentation website. No participant inputs."""
from pathlib import Path
from html import escape
import argparse, hashlib, json, sys
ROOT=Path(__file__).resolve().parent.parent
sys.path.insert(0,str(ROOT/'activity'))
from render import reflection_content

def render_site(root=ROOT):
    config=json.loads((root/'site.json').read_text(encoding='utf8'))
    data=json.loads((root/'activity/reflection.json').read_text(encoding='utf8'))
    base=config['url']
    if config['mode'] not in {'presentation','retired'}:raise ValueError('Unsupported site mode')
    if config['mode']=='retired':
        target=config['returnUrl']
        redirect=f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Digital Citizen Reflection has moved</title><meta name="robots" content="noindex"><link rel="canonical" href="{escape(target)}"><meta http-equiv="refresh" content="0;url={escape(target)}"></head><body><h1>Digital Citizen Reflection</h1><p>The activity is now available in Signal &amp; Self.</p><a href="{escape(target)}">Open the activity</a><script>window.location.replace({json.dumps(target)});</script></body></html>\n'
        return {name:redirect for name in ['index.html','evidence.html','resources.html','privacy.html','accessibility.html','script.html','404.html']}|{'sitemap.xml':'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>\n','robots.txt':'User-agent: *\nDisallow: /\n'}
    def asset(path):
        digest=hashlib.sha256((root/path).read_bytes()).hexdigest()[:10]
        return path+'?v='+digest
    nav=[('Activity','index.html#reflection-activity'),('Evidence','evidence.html'),('Resources','resources.html'),('Privacy','privacy.html')]
    reading_ui='''<details class="reading-options site-shell js-only" id="reading-options" hidden><summary>Accessibility options</summary><div class="reading-panel"><p>Adjust how the site looks. These options do not change your answers.</p><div class="reading-controls"><label for="reading-size">Text size<select id="reading-size"><option value="standard">Standard</option><option value="large">Large</option><option value="extra-large">Extra large</option></select></label><label for="reading-contrast"><input type="checkbox" id="reading-contrast">Stronger contrast</label><label for="reading-spacing"><input type="checkbox" id="reading-spacing">More text spacing</label><label for="reading-motion"><input type="checkbox" id="reading-motion" aria-describedby="motion-note">Reduce motion</label></div><p class="field-hint" id="motion-note">Your device's reduced-motion preference is always respected.</p><div class="reading-actions"><button type="button" class="button button-quiet" id="reading-reset">Reset reading options</button><a href="accessibility.html">Keyboard and accessibility guide</a></div><p id="reading-status" role="status">Viewing options are remembered on this device. Reflection answers save only if you choose.</p></div></details>'''
    def page(title,body,name,activity=False):
        links=''.join(f'<a href="{href}"'+(' aria-current="page"' if name==href.split('#')[0] else '')+f'>{label}</a>' for label,href in nav)
        scripts=f'<script src="{asset("assets/scripts/ui.js")}" defer></script>'
        if activity:scripts+=f'<script src="{asset("activity/reflection.js")}" defer></script><script src="{asset("activity/guidance.js")}" defer></script>'
        canonical=base+('' if name=='index.html' else name)
        description='A private four-step activity to observe an online habit, evaluate evidence, identify a risk, and choose a realistic change.'
        schema={'@context':'https://schema.org','@type':'WebApplication','name':'Digital Citizen Reflection','url':base,'applicationCategory':'EducationalApplication','isAccessibleForFree':True,'inLanguage':'en'}
        return f'''<!doctype html><html lang="en" data-theme="signal"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} — Digital Citizen Reflection</title><meta name="description" content="{description}"><meta name="theme-color" content="#f4f0e8"><meta name="referrer" content="no-referrer"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{escape(title)} — Digital Citizen Reflection"><meta property="og:description" content="{description}"><meta property="og:url" content="{canonical}"><meta property="og:type" content="website"><link rel="preload" href="assets/fonts/newsreader-600.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/manrope-400.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="{asset('assets/styles/fonts.css')}"><link rel="stylesheet" href="{asset('assets/styles/base.css')}"><link rel="stylesheet" href="{asset('assets/styles/project.css')}"><link rel="stylesheet" href="{asset('assets/styles/reflection.css')}"><link rel="stylesheet" href="{asset('assets/styles/layout.css')}"><link rel="stylesheet" href="{asset('assets/styles/accessibility.css')}">{scripts}<script type="application/ld+json">{json.dumps(schema).replace('<',chr(92)+'u003c')}</script></head><body id="top"><a class="skip-link" href="#main-content">Skip to content</a><header class="site-header site-shell"><a class="wordmark" href="index.html">Digital Citizen Reflection</a><nav class="site-nav" aria-label="Primary navigation">{links}</nav><div class="theme-control js-only" hidden><label for="theme">Theme</label><select id="theme"><option value="signal">Signal</option><option value="midnight">Midnight</option><option value="quiet">Quiet</option></select></div></header>{reading_ui}<main id="main-content" tabindex="-1">{body}</main><footer class="site-footer site-shell"><span>Digital Citizen Reflection</span><a href="privacy.html">Privacy &amp; your controls</a><a href="resources.html">Worksheet &amp; session materials</a><a href="accessibility.html">Accessibility</a><a href="#top">Back to top</a></footer></body></html>\n'''
    def intro(title,text):return f'<section class="page-hero site-shell"><p class="eyebrow">Digital Citizen Reflection</p><h1>{title}</h1><p class="page-lede">{text}</p></section>'
    cards=''
    for s in data['sources']:
        cards+=f'<article class="reflection-source"><p class="mono-label">{escape(s["publisher"])}</p><h2>{escape(s["title"])}</h2><p><strong>Date:</strong> {escape(s["date"])}</p><p>{escape(s["finding"])}</p><p><strong>Population / audience:</strong> {escape(s["population"])}</p><p><strong>Limit:</strong> {escape(s["limit"])}</p><p>{escape(s["prompt"])}</p><a href="{escape(s["url"])}" rel="noreferrer" aria-label="Read the original source: {escape(s["title"])}, {escape(s["publisher"])}">Read the original source</a></article>'
    downloads=[('digital-citizen-worksheet.pdf','One-page worksheet','Printable prompts and sentence starters for all four steps.','PDF'),('digital-citizen-presentation.pptx','Editable presentation','Ten slides with speaker notes and screenshots for an offline demonstration.','PowerPoint'),('digital-citizen-presentation.pdf','Presentation slides','The ten slides, with speaker notes attached as PDF comments.','PDF'),('digital-citizen-presenter-guide.pdf','Presenter guide','Readable notes, live-demo cues, and the five-minute condensed script.','PDF')]
    resource_list=''.join(f'<li><h2>{label}</h2><p>{text}</p><a class="button button-quiet" href="assets/downloads/{file}">Download {label.lower()} ({kind})</a></li>' for file,label,text,kind in downloads)
    privacy=intro('Your answers stay with you','The activity and guided helper run in this browser. No sign-in is required.')+'''<section class="section site-shell"><h2>Temporary unless you choose to save</h2><p>Reflection answers stay in memory until you enable Save on this device. Then drafts save automatically in this browser. Choose Resume to open a saved draft. Disabling saving removes it while keeping the current answers on the page. Clear reflection removes both.</p><p>Saved reflections do not sync between devices. People sharing this browser profile may see saved drafts. GitHub project sites on the same host share a browser storage origin; the activity keeps its existing reflection key so compatible drafts can resume when it returns to Signal &amp; Self. It does not read portfolio identity, names, goals, saved items, or personalization.</p><h2>Help that you control</h2><p>Guided help uses prepared questions and sentence starters, not an external AI service. It opens only when you request it or accept an offer. An empty focused field or repeated missing-answer checks can trigger a small offer; this does not judge your writing. No thanks stops proactive offers for this visit.</p><p>Timers and offer counts remain in memory. No typing history is recorded. Unfinished helper responses are temporary; only a draft you explicitly use becomes part of the reflection and its saving controls.</p><h2>Theme and reading options</h2><p>The theme, text size, contrast, spacing, and reduced-motion choices are remembered in separate project-only browser storage. These viewing choices contain no reflection text. Reset reading options removes the saved reading choices without changing your theme or answers. If storage is blocked, viewing choices still work for the current visit.</p><h2>No reflection submission</h2><p>Answers, helper responses, and difficulty signals are never added to URLs, analytics, network requests, or sign-in state. This website has no analytics beacon, Google identity scripts, cloud account, or submission endpoint. GitHub Pages serves the public files and may keep standard hosting security logs; those requests do not contain reflection answers.</p><p>Source links leave the site with no referrer. Downloads and printouts contain the answers you choose to keep. Keep or share them as you prefer.</p><h2>If saving is unavailable</h2><p>The activity remains usable temporarily and explains that draft saving failed. You can still download or print an action plan. Clearing browser data also removes saved drafts.</p></section>'''
    outputs={
        'index.html':page('Activity',reflection_content(data,worksheet='assets/downloads/digital-citizen-worksheet.pdf',project_only=True),'index.html',True),
        'evidence.html':page('Evidence',intro('Evidence and its limits','A credible source can help you think without answering every question about your own situation.')+f'<section class="section site-shell reflection-sources">{cards}</section>','evidence.html'),
        'resources.html':page('Resources',intro('Take the framework with you','Use the worksheet, editable slides, or an offline presentation backup.')+f'<section class="section site-shell"><ul class="resource-list">{resource_list}</ul><figure class="resource-qr"><img src="assets/downloads/activity-qr.png" width="180" height="180" loading="lazy" alt="QR code for the Digital Citizen Reflection activity"><figcaption><strong>A link to share</strong><p>This QR code opens the activity. You can use the same link without scanning it.</p><a href="index.html">Open Digital Citizen Reflection</a></figcaption></figure><p><a href="script.html">Read the presentation scripts as accessible web text</a></p></section>','resources.html'),
        'privacy.html':page('Privacy',privacy,'privacy.html'),
        'accessibility.html':page('Accessibility',intro('Make the activity work for you','Use the keyboard, adjust the reading options, or take the worksheet to paper.')+'''<section class="section site-shell access-copy"><h2>Choose how you read</h2><p>Open Accessibility options near the top of any page for larger text, more text spacing, stronger contrast, or reduced motion. All three themes remain available. Your device's reduced-motion setting is always respected. You can also use your browser's zoom. Reset reading options restores the standard reading choices without clearing your reflection.</p><h2>Use the keyboard</h2><p>Press Tab to move forward and Shift + Tab to move back. The first link skips to the main content. Press Enter on a button or link. Press Space on a checkbox or a disclosure such as Accessibility options. Use your arrow keys to choose a topic, theme, or text size. A visible outline shows where you are.</p><p>Reflection step buttons let you move backward and edit your answers. Help opens only when you request it. Press Escape inside help or Accessibility options to close it and return to its opening button. You can also use Close help.</p><h2>Read with assistive technology</h2><p>Fields have visible labels and associated hints. The current step is identified in text and announced when you navigate. Missing answers have a written explanation linked to the field. Source links name the source they open. The time comparison is available as text; its bars repeat the same information. The QR code has a text description and an equivalent activity link.</p><h2>Prefer paper or plain text?</h2><p><a href="assets/downloads/digital-citizen-worksheet.pdf">Download the one-page worksheet (PDF)</a>, or print the activity page with JavaScript disabled. After completing an action plan, you can download its plain text or print it. <a href="script.html">Presentation scripts are available as web text</a> alongside the PowerPoint and PDFs.</p><h2>Your pace and your words</h2><p>There is no deadline for an answer. Short responses, uncertainty, and unchanged habits are welcome. Optional help offers do not open automatically or move your focus. No thanks stops proactive offers for the current visit. Viewing options do not change your answers or enable draft saving.</p></section>''','accessibility.html'),
        '404.html':page('Page not found',intro('Page not found','Start again with the activity, evidence, or resources.')+'<p class="site-shell"><a href="index.html">Open the activity</a></p>','404.html').replace('<head>','<head><base href="'+base+'">'),
    }
    scripts_file=root/'docs/presentation/speaker-scripts.json'
    scripts=json.loads(scripts_file.read_text(encoding='utf8')) if scripts_file.exists() else {'slides':[],'backup':[]}
    script_body=intro('Presentation scripts','Ten-minute session and five-minute offline version.')
    for title,items,key in [('Ten-minute session',scripts.get('slides',[]),'notes'),('Five-minute backup',scripts.get('backup',[]),'text')]:
        script_body+=f'<section class="section site-shell"><h2>{title}</h2>'
        for s in items:script_body+=f'<h3>{escape(s.get("title",s.get("time","")))}</h3><p>{escape(s.get(key,""))}</p>'
        script_body+='</section>'
    outputs['script.html']=page('Presentation scripts',script_body,'script.html')
    outputs['robots.txt']='User-agent: *\nAllow: /\nSitemap: '+base+'sitemap.xml\n'
    outputs['sitemap.xml']='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+base+('' if p=='index.html' else p)+'</loc></url>' for p in outputs if p.endswith('.html') and p!='404.html')+'</urlset>\n'
    return outputs

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    outputs=render_site();different=[]
    for name,text in outputs.items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf8')!=text:different.append(name)
        else:path.write_text(text,encoding='utf8',newline='\n')
    if different:raise SystemExit('Generated files differ: '+', '.join(different))
    print(('Checked' if args.check else 'Generated')+f' {len(outputs)} public files.')
if __name__=='__main__':main()
