"""Static content and progressively enhanced reflection worksheet."""
from html import escape as e


def reflection_content(data, worksheet='../assets/downloads/digital-citizen-worksheet.pdf', project_only=False):
    topics = ''.join(f'<option value="{t["id"]}">{e(t["label"])}</option>' for t in data['topics'])
    examples = ''.join(f'<details class="reflection-example"><summary>{e(t["label"])}</summary><p>{e(t["description"])}</p><p><strong>Fictional observation:</strong> {e(t["example"]["observation"])}</p></details>' for t in data['topics'])
    cards = ''.join(f'''<article class="reflection-source" data-source-topics="{' '.join(s['topics'])}"><p class="mono-label">{e(s['publisher'])}</p><h3>{e(s['title'])}</h3><div class="evidence-pair"><section><h4>What this source supports</h4><p>{e(s['finding'])}</p></section><section><h4>What it cannot tell us</h4><p>{e(s['limit'])}</p></section></div><details><summary>About this source</summary><p><strong>Date:</strong> {e(s['date'])}</p><p><strong>Population / audience:</strong> {e(s['population'])}</p></details><p class="source-question">{e(s['prompt'])}</p><a href="{e(s['url'])}" rel="noreferrer" aria-label="Read the original source: {e(s['title'])}, {e(s['publisher'])}">Read the original source</a></article>''' for s in data['sources'])
    overview = '''<aside class="reflection-overview" aria-labelledby="overview-title"><p class="eyebrow">A small change starts here</p><h2 id="overview-title">Keep what helps.<br> Change what gets in the way.</h2><ol><li><strong>Observe</strong><span>Notice one online habit.</span></li><li><strong>Evaluate</strong><span>Compare evidence and its limits.</span></li><li><strong>Identify</strong><span>Keep a benefit. Name a risk.</span></li><li><strong>Act</strong><span>Choose one change to try.</span></li></ol></aside>''' if project_only else ''
    def guidance(id, label):
        item=data.get('guidance',{}).get(id)
        if not item: return ''
        questions=''.join(f'<li>{e(p["question"])} <span class="field-hint">Sentence starter: {e(p["starter"])} …</span></li>' for p in item['prompts'])
        return f'''<details class="guidance-fallback"><summary>Ideas to help you answer</summary><ol>{questions}</ol></details>
<div class="guidance" data-guidance-id="{id}"><button type="button" class="button button-quiet guidance-open js-only" hidden aria-expanded="false" aria-controls="helper-{id}-panel">Help me answer<span class="visually-hidden">: {e(label)}</span></button>
<div class="guidance-offer" hidden><p role="status">Would you like a prompt?</p><button type="button" class="button button-quiet" data-help-accept>Show help</button> <button type="button" class="button button-quiet" data-help-dismiss>No thanks</button></div>
<section class="guidance-panel" id="helper-{id}-panel" hidden aria-labelledby="helper-{id}-title"><h4 id="helper-{id}-title">Develop your answer</h4><p>Prepared prompts, not AI. Your words stay in this browser. Helper responses are temporary until you use the draft in your reflection.</p><p class="field-hint" data-help-hint></p><p data-help-progress role="status"></p>
<div data-help-question-area><label for="helper-{id}-answer" data-help-question></label><p class="field-hint" data-help-starter></p><textarea autocomplete="off" id="helper-{id}-answer" rows="2" maxlength="400"></textarea><div class="button-row"><button class="button button-quiet" type="button" data-help-uncertain>I'm not sure</button><button class="button button-quiet" type="button" data-help-nochange hidden>No change</button><button class="button button-quiet" type="button" data-help-skip>Skip this prompt</button></div></div>
<div data-help-preview hidden><label for="helper-{id}-draft">Draft preview · edit before using</label><textarea autocomplete="off" id="helper-{id}-draft" rows="5" maxlength="1500"></textarea><p class="field-hint">This draft uses only your prompt responses. Check that it says what you mean.</p><div class="button-row"><button type="button" class="button button-primary" data-help-use>Use this draft</button><button type="button" class="button button-primary" data-help-append>Append to my answer</button><button type="button" class="button button-quiet" data-help-replace>Replace my answer</button></div></div>
<p data-help-message role="status"></p><div class="button-row"><button type="button" class="button button-quiet" data-help-back>Previous prompt</button><button type="button" class="button button-primary" data-help-next>Next prompt</button><button type="button" class="button button-quiet" data-help-close>Close help</button></div></section>
<div data-help-undo hidden><p role="status">Draft added. You can keep editing your answer.</p><button type="button" class="button button-quiet" data-help-undo-button>Undo last helper insertion</button></div></div>'''
    def field(id, label, hint='', required=True):
        marker = 'Required' if required else 'Optional'
        return f'<div class="form-field"><label for="{id}"><span data-field-label>{label}</span> <span class="field-requirement" data-field-requirement>{marker}</span></label><textarea autocomplete="off" id="{id}" name="{id}" rows="3" maxlength="1500"{ " required" if required else ""}{f" aria-describedby={id}-hint" if hint else ""}></textarea>{f"<p class=field-hint id={id}-hint>{hint}</p>" if hint else ""}{guidance(id,label)}</div>'
    return f'''<section class="page-hero site-shell reflection-hero"><div class="reflection-intro"><p class="eyebrow">{'A private guided activity' if project_only else 'A Signal &amp; Self activity'} · about 5 minutes</p><h1>Digital Citizen<br><span class="serif-italic">Reflection</span></h1><p class="page-lede">Turn one online habit into evidence and action. Keep what helps you. Choose one thing to change.</p><div class="button-row intro-choices"><a class="button button-primary" id="reflection-start-own" href="#reflection-activity">Reflect on my habit</a><a class="button button-quiet" id="reflection-start-example" href="#examples-title">Try a fictional example</a></div></div>{overview}</section>
<section class="section site-shell reflection-shell" id="reflection-activity" aria-labelledby="activity-title"><div class="activity-heading"><div><p class="eyebrow">Your reflection</p><h2 id="activity-title">One habit. Four steps.</h2><p>Short answers are enough. You can start with a fictional example or write “I'm not sure yet.”</p></div><a class="button button-quiet worksheet-link" href="{e(worksheet)}">Printable worksheet <span class="file-type">PDF</span></a></div>
<div class="reflection-storage js-only" hidden><label><input autocomplete="off" type="checkbox" id="reflection-save" aria-describedby="reflection-storage-status"> Save on this device</label><button class="button button-quiet" type="button" id="reflection-clear">Clear reflection</button><p id="reflection-storage-status" role="status">Temporary reflection. Your answers are not saved.</p><details class="storage-explainer"><summary>How saving works</summary><p>When enabled, drafts save automatically in this browser. They do not sync across devices. On a shared device, others using this browser may see them. Turn saving off to remove the stored draft while keeping your current answers.</p></details><div id="reflection-resume" hidden><p>A saved reflection is available on this device.</p><button class="button button-primary" type="button" id="reflection-resume-button">Resume saved reflection</button></div><p id="reflection-clear-confirm" hidden>Clear your answers and the saved draft? <button class="button button-quiet" id="reflection-clear-yes" type="button">Yes, clear</button> <button class="button button-quiet" id="reflection-clear-no" type="button">Keep reflection</button></p></div>
<p class="reflection-nojs">This worksheet works on paper too. With JavaScript disabled, read the sources and print this page to write your answers.</p>
<nav aria-label="Reflection steps" class="reflection-steps js-only" hidden>{''.join(f'<button type="button" data-reflection-step="{i}"><span class="step-number">{i+1}</span><span class="step-name">{label}<span class="step-current" aria-hidden="true">Current step</span></span></button>' for i,label in enumerate(['Observe','Evaluate','Identify','Act']))}</nav>
<p id="reflection-progress" class="mono-label js-only" role="status" hidden></p>
<div id="reflection-form" role="form" aria-label="Reflection questions">
<p class="field-hint required-explanation">Fields marked <strong>Required</strong> are needed to build your plan. Short answers and “I'm not sure yet” are welcome.</p>
<p id="reflection-error-summary" class="field-error" role="alert" hidden></p>
<section class="reflection-step" data-step="0" aria-labelledby="observe-title"><h3 id="observe-title" tabindex="-1">1 · Observe a habit</h3><p>Choose a topic, then describe something specific. You can begin with a fictional example.</p><label class="form-field" for="reflection-topic">Topic <span class="field-requirement">Required</span><select autocomplete="off" id="reflection-topic" name="topic" required>{topics}</select></label><div class="button-row js-only" hidden><button type="button" id="reflection-example" class="button button-quiet">Use fictional example</button><button type="button" id="reflection-own" class="button button-quiet">Start my own reflection</button></div><p id="reflection-mode" role="status">Your own reflection · no example loaded</p><div id="reflection-switch-confirm" hidden><p>Starting another topic or example replaces your current answers.</p><button type="button" class="button button-primary" id="reflection-switch-yes">Replace answers</button> <button type="button" class="button button-quiet" id="reflection-switch-no">Keep current answers</button></div>
{field('observation','What do you do online?','Describe one habit; avoid names or private details.')}{field('context','When or where does it happen?')}{field('notice','What do you notice afterward?','Consider benefits as well as things that get in the way.')}
<div id="attention-comparison"><h4>Time comparison · optional</h4><div class="reflection-time"><label for="before">Current minutes per day <span class="field-requirement">Optional</span><input autocomplete="off" id="before" name="before" type="number" min="0" max="1440" step="1" inputmode="numeric"></label><label for="after">Planned minutes per day <span class="field-requirement">Optional</span><input autocomplete="off" id="after" name="after" type="number" min="0" max="1440" step="1" inputmode="numeric"></label></div><p id="reflection-arithmetic" role="status">Enter both values to compare them. These are arithmetic estimates, not health recommendations.</p><div class="reflection-bars" aria-hidden="true"><span id="before-bar"></span><span id="after-bar"></span></div></div></section>
<section class="reflection-step" data-step="1" aria-labelledby="evaluate-title"><h3 id="evaluate-title" tabindex="-1">2 · Evaluate the evidence</h3><p>Read the evidence relevant to your topic. Compare a finding with its limits: a source can be credible without answering every question.</p><div class="reflection-sources">{cards}</div>{field('evidenceResponse','What does the evidence help you understand?','What can it support, and what would you still need to check about your own situation?')}</section>
<section class="reflection-step" data-step="2" aria-labelledby="identify-title"><h3 id="identify-title" tabindex="-1">3 · Identify a risk</h3><label class="form-field" for="risk">What risk do you want to address? <span class="field-requirement">Required</span><select autocomplete="off" id="risk" name="risk" required><option value="">Choose a risk</option><option value="other">Describe my own risk</option></select></label>{field('riskDetail','Describe the risk','Use this to add context or describe your own risk.',False)}{field('benefit','What benefit do you want to keep?','A change can preserve connection, creativity, learning, or another benefit you value.')}</section>
<section class="reflection-step" data-step="3" aria-labelledby="act-title"><h3 id="act-title" tabindex="-1">4 · Choose a realistic change</h3>{field('change','What is one change you will try?','Make it small enough to try in your real routine.')}{field('check','How will you check what happens?','Choose an observable check, such as whether you found the original source before sharing.')}<label class="form-field" for="reviewDate">When will you review it? <span class="field-requirement">Required</span><input autocomplete="off" type="date" id="reviewDate" name="reviewDate" required></label><button type="button" class="button button-primary js-only" id="reflection-finish" hidden>Build my action plan</button></section>
<div class="reflection-navigation js-only" hidden><button type="button" id="reflection-back" class="button button-quiet">Back</button><button type="button" id="reflection-next" class="button button-primary">Next step</button></div></div>
<section id="reflection-summary" hidden aria-labelledby="summary-title"><h3 id="summary-title" tabindex="-1">Your action plan</h3><p id="summary-mode"></p><dl id="summary-content"></dl><details id="summary-supporting"><summary>The reflection behind my plan</summary><dl id="summary-reflection"></dl></details><div class="button-row"><button type="button" class="button button-quiet" id="reflection-edit">Edit my answers</button><button type="button" class="button button-primary" id="reflection-download">Download text</button><button type="button" class="button button-quiet" id="reflection-print">Print action plan</button></div><p>Keep the benefit. Try the change. Review what actually happened.</p></section></section>
<section class="section site-shell reflection-examples" aria-labelledby="examples-title"><h2 id="examples-title">Four ways to begin</h2><p>All examples are fictional.</p>{examples}</section>
<script type="application/json" id="reflection-data">{__import__('json').dumps(data,ensure_ascii=False).replace('<',chr(92)+'u003c')}</script>'''
